languageCode = "en-us"
title = "Unbounded School"
baseURL = "https://unbounded.school"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Quests and Progress for Unbounded School"
  codePenUser = "veeneck"
