languageCode = "en-us"
title = "Unbounded School"
baseURL = "https://unbounded.school"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = ""
  codePenUser = "veeneck"
  
[markup.goldmark.renderer]
  unsafe = true
